home/models.py, home/templates/home/blocks/heading.html, home/templates/home/blocks/logo.html, home/templates/home/blocks/quote.html, home/templates/home/blocks/table.html, home/templates/home/home_page.html
=> Clean up StreamField templates; add header anchors

outreachyhome/templates/base.html
Howdy Sage! This is the update we discussed during our call earlier today.
=> Update github link in footer

home/templates/home/snippet/time_commitment_overview.html
=> Fix typo in line 7

outreachyhome/templates/base.html
@sagesharp  - This is the Basic Implementation for the issue: https://github.com/sagesharp/outreachy-django-wagtail/issues/240
I used the latest image URL you gave me. Let me know what you think about it!
I'll work on the blog post one separately since that might need some more time to figure out.
=> Adding Twittercard and Open Graph meta tags

outreachyhome/templates/base.html, outreachyhome/templates/partials/_footer.html, outreachyhome/templates/partials/_navigation.html, outreachyhome/templates/sass/_config.scss, outreachyhome/templates/sass/_fonts.scss, outreachyhome/templates/sass/application.scss
* moves footer markup into it's own partial: `templates/partials/_footer.html`
* moves navbar `<ul>` markup into it's own partial `templates/partials/_navigation.html`
* fixes issue where the anchor links need more spacing when navigating to an inline link on the same page #249 
* removes the white spacing at the bottom of the footer
* removes transparency in the navigation links
* organizes scss/css into partials
=> Minor Front-End Improvements

home/templates/home/dashboard/intern.html
Just Found it while going through my dashboard.
=> Fixed typo in contract spelling

README.md
This pull request tests Travis CI integration after the move to a new Outreachy organization on GitHub.
=> GitHub migration

home/templates/home/snippet/project_landing_snippet.html, home/views.py
=> Add a comma to the template unless its the last email address

home/templates/home/snippet/pending_prompt.html
Fixes #286
Seems like if the organizers think the essays are unclear, they will not be reviewing the application.
=> Add prompt for Applicant to update their Application

home/templates/home/eligibility_results.html, home/templates/home/set_gmail_filters_warning.html
Warning is to set gmail filters so that Students can find their emails.
Fixes #285
=> Add warning on Eligibility Results page

home/email.py, home/templates/home/email/new-community-created.txt, home/views.py
Template info copied from participation-pending.txt. The content probably needs to be edited but does not include Participation data because we don't have that yet. Lots of duplication between the two files. But here is a jumping off point.
Related to #305
=> Send email when New Community created

home/test_internselection.py, home/views.py
Mentor approval, coordinator funding selection, and organizer approval.  And fix the bug that organizers could approve an un-funded intern.
=> Check the entire intern approval process

home/templates/home/docs/applicant_guide.html
I noticed that my blog was mentioned on the website but unfortunately the links don't work since I moved to medium
=> Update blog link

README.md
Fix a small grammar mistake I found when trying to fix another grammar mistake :sweat_smile: 
The other one is on the current front page - "Outreachy **is will** be looking for FOSS communities" - but I couldn't find it in the code, so assuming it's handled by on Wagtail?
=> Fix grammar mistake

home/templates/home/community_read_only.html
"contribution person" --> "contribution period"
=> Fixed typo.

home/templates/home/email/interns-notify.txt
This fixes [#474](https://github.com/outreachy/website/issues/474)
=> Removes travel stipend in intro email

home/templates/home/email/mentor-applicant-updates.txt
Update the mentor-applicant-updates.txt email template to include a project promotion section.
=> Update mentor-applicant-updates.txt email template

home/templates/home/email/mentor-application-deadline-approaching.txt
This PR updates the mentor reminder email to reflect revised project guidelines for final applications.
=> Update mentor email for final applications to reflect updated applicant docs

docs/mentor-agreement.md
While signing up the mentorship agreement, one of the OISF mentors noticed that the dates were still for the previous round.
Updated all references that seemed related to the previous round.
Also put the internship duration in bold, to help highlight it a bit.
=> Update mentor-agreement for December 2024 round

home/constants.py, home/models.py
Fix skill validation to allow valid skills like "Machine Learning" and "UIUX"
- Updated skill validation logic to avoid flagging valid skills containing words like "learn" and "learning".
- Removed "/" from the UI/UX skill to allow the skill pass validation
=> Fix skill validation to allow valid skills like "Machine Learning"
